"""
API schemas for Character.

These schemas are separated from the domain model so API contracts can evolve
without forcing direct changes in domain-layer imports everywhere.
"""

from typing import Self

from pydantic import BaseModel, ConfigDict, Field, model_validator

from app.models.character import Character


class CharacterCreate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    """
    Payload expected from API clients when creating a character.
    `id` is intentionally absent: it is generated by the domain model.
    """

    name: str = Field(..., min_length=1)
    race: str = Field(..., min_length=1)
    class_name: str = Field(..., min_length=1)
    level: int = Field(..., ge=1, le=20)
    max_hp: int = Field(..., gt=0)
    hp: int = Field(..., ge=0)
    inventory: list[str] = Field(default_factory=list)
    skills: list[str] = Field(default_factory=list)
    strength: int = Field(..., ge=1, le=30)
    dexterity: int = Field(..., ge=1, le=30)
    constitution: int = Field(..., ge=1, le=30)
    intelligence: int = Field(..., ge=1, le=30)
    wisdom: int = Field(..., ge=1, le=30)
    charisma: int = Field(..., ge=1, le=30)

    @model_validator(mode="after")
    def hp_cannot_exceed_max_hp(self) -> Self:
        if self.hp > self.max_hp:
            raise ValueError(
                f"hp ({self.hp}) cannot exceed max_hp ({self.max_hp})"
            )
        return self


class CharacterResponse(Character):
    model_config = ConfigDict(from_attributes=True, extra="forbid")
    """
    API response schema for character payloads.
    Includes id and inherits full domain validation.
    """


class CharacterUpdate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    """
    Partial update payload.
    All fields are optional so clients can send only changed values.
    """

    name: str | None = Field(default=None, min_length=1)
    race: str | None = Field(default=None, min_length=1)
    class_name: str | None = Field(default=None, min_length=1)
    level: int | None = Field(default=None, ge=1, le=20)
    max_hp: int | None = Field(default=None, gt=0)
    hp: int | None = Field(default=None, ge=0)
    inventory: list[str] | None = None
    skills: list[str] | None = None
    strength: int | None = Field(default=None, ge=1, le=30)
    dexterity: int | None = Field(default=None, ge=1, le=30)
    constitution: int | None = Field(default=None, ge=1, le=30)
    intelligence: int | None = Field(default=None, ge=1, le=30)
    wisdom: int | None = Field(default=None, ge=1, le=30)
    charisma: int | None = Field(default=None, ge=1, le=30)

    @model_validator(mode="after")
    def hp_cannot_exceed_max_hp_when_both_provided(self) -> Self:
        if self.hp is not None and self.max_hp is not None and self.hp > self.max_hp:
            raise ValueError(
                f"hp ({self.hp}) cannot exceed max_hp ({self.max_hp})"
            )
        return self
